#!/bin/bash

# : ${MIRROR_REGISTRY:=registry.cn-shanghai.aliyuncs.com}
: ${MIRROR_REGISTRY:=registry.cn-hongkong.aliyuncs.com/cmi}

# sync-image argoproj/argocd $(github-latest-version argoproj/argo-cd)
sync-image(){
  # cmi - container mirror image
  local target=$MIRROR_REGISTRY
  
  

  # argoproj/argocd -> docker.io/argoproj/argocd
  # if [[ $(echo $1 |tr -d -c '/' | wc -c) = 1 ]]; then
  #  $1="docker.io/$1"
  # fi

  local name=$1
  local ver=$2

  [ -n "$ver" ] || {
    echo "sync-image <name> <tag>";
    return 1
  }

  local src=${name%%/*}
  name=${name##$src/}
#  if [ $src = "k8s.gcr.io" ]; then
#    src="gcr.io"
#    name="google-containers/${name}"
#  fi

  # argoproj/argocd -> argoproj_argocd
  local target_name=${name//\//_}

  local src_repo=$src/$name:$ver
  local target_repo=$target/$target_name:$ver

  echo "sync $1:$2 -> $target_repo"

  local sync=
  if [ "$ver" = "latest" ]; then
    sync=1
  else
    DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $target_repo &> /dev/null || {
      sync=1
    }
  fi
  
  if [ -n "$sync" ]; then 
    _sync_image $src_repo $target_repo
    [ $ver == "latest" ] || {
      echo -n "update $target_name:$ver ;" >> message
      echo "| $1 | $2 | $target_name | $(date +"%Y-%m-%d %H:%M:%S") |" >> CHANGELOG.md
    }
  fi
}

_sync_image(){
  echo Syncing $1 to $2

  docker pull $1
  docker tag $1 $2
  docker push $2
}

if [ $(basename $0) = "sync-image" ]; then
  sync-image "$@"
fi
