#!/bin/bash

# : ${MIRROR_REGISTRY:=registry.cn-shanghai.aliyuncs.com}
: ${MIRROR_REGISTRY:=registry.cn-hongkong.aliyuncs.com/cmi}

sync-image(){
  # cmi - container mirror image
  local target=$MIRROR_REGISTRY

  local name=$1
  local ver=$2

  [ -n "$ver" ] || {
    echo "sync-image <name> <tag>";
    return 1
  }

  local src=${name%%/*}
  name=${name##$src/}
#  if [ $src = "k8s.gcr.io" ]; then
#    src="gcr.io"
#    name="google-containers/${name}"
#  fi

  local target_name=${name//\//_}

  local src_repo=$src/$name:$ver
  local target_repo=$target/$target_name:$ver

  echo "Checking $1:$2 -> $target_repo"

  local sync=
  if [ "$ver" = "latest" ]; then
    sync=1
  else
    DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $target_repo &> /dev/null || {
      sync=1
    }
  fi
  
  if [ -n "$sync" ]; then 
    _sync_image $src_repo $target_repo
    [ $ver == "latest" ] || {
      echo -n "update ${1%%/*}:$ver ." >> message
      echo "| $1 | $2 | $target_name | $(date +"%Y-%m-%d %H:%M:%S") |" >> CHANGELOG.md
    }
  fi
}

_sync_image(){
  echo Syncing $1 to $2

  docker pull $1
  docker tag $1 $2
  docker push $2
}

if [ $(basename $0) = "sync-image" ]; then
  sync-image "$@"
fi
