name: Sync

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        # ref: ${{ github.head_ref }}
        ref: master
    - uses: imjasonh/setup-crane@v0.1

    - name: login
      run: |
        #docker login -u ${{ secrets.ALI_REGISTRY_USER }} -p ${{ secrets.ALI_REGISTRY_PASSWORD }} registry.cn-shanghai.aliyuncs.com
        docker login -u ${{ secrets.ALI_REGISTRY_USER }} -p ${{ secrets.ALI_REGISTRY_PASSWORD }} registry.cn-hongkong.aliyuncs.com

    - name: synching
      run: |
        bash ./scripts/sync.sh
        touch message

    - name: Generate Commit Message
      run: |
        echo "##[set-output name=message;]$(cat message)"
      id: generate_commit_message

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ steps.generate_commit_message.outputs.message }}

        commit_user_name: Wener Bot
        commit_user_email: wenerbot@gmail.com
        commit_author: GitHub Actions <wenerbot@gmail.com>
